default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: "cj_development"
  username: "postgres"
  password: "123456789"
  host: localhost

production:
  <<: *default
  database: "cj_production"
  username: "postgres"
  password: "123456789"
  host: localhost

test:
  <<: *default
  database: "travis_ci_test"
  username: travis

